services:
  prometheus:
    image: prom/prometheus:latest
    container_name: java-data-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: java-data-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: java-data-mysql-exporter
    ports:
      - "9104:9104"
    command:
      - "--mysqld.username=root"
      - "--mysqld.address=host.docker.internal:3306"
    environment:
      - MYSQLD_EXPORTER_PASSWORD=1234
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - prometheus
