spring.application.name=java-data

# mysql
spring.datasource.url=jdbc:mysql://localhost:3306/weather?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

# ???? - ??
safety.api.base-url=https://www.safetydata.go.kr/V2/api/DSSP-IF-00183
safety.api.service-key=G052T1JS73F7O77Q

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

# Tomcat 커넥션 설정
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20
server.tomcat.max-connections=8192
server.tomcat.accept-count=200

# 기상특보 API
weather.warn.api.base-url=https://apis.data.go.kr/1360000/WthrWrnInfoService/getWthrWrnList
weather.warn.api.service-key=3654614ea0f0bad6523bc7c66b8ae5b229fc5b9a75cd783d4f69b768b989f562

# 관광 방문자 API
tourism.api.base-url=https://apis.data.go.kr/B551011/DataLabService/metcoRegnVisitrDDList
tourism.api.service-key=3654614ea0f0bad6523bc7c66b8ae5b229fc5b9a75cd783d4f69b768b989f562

# 공휴일 API
holiday.api.base-url=https://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo
holiday.api.service-key=3654614ea0f0bad6523bc7c66b8ae5b229fc5b9a75cd783d4f69b768b989f562

# 에어코리아 대기오염 API
airquality.api.base-url=https://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getCtprvnRltmMesureDnsty
airquality.api.service-key=3654614ea0f0bad6523bc7c66b8ae5b229fc5b9a75cd783d4f69b768b989f562
airquality.api.sido-name=\uc11c\uc6b8
